### ISSUE TITLE
震级计算

### ISSUE THREAD

**Issue by Ma-yuan-science** [MrXiaoXiao/ESPRH#1]
您好，请问在构建地震目录中，您是如何计算震级的，该流程似乎没有震级计算的步骤

**Comment by MrXiaoXiao** [comment]
目前公开代码里面没加，您可以利用拾取的走时截取对应的波形片段来计算震级，这里以里氏震级为例简单介绍下：

1.在EqT + S-EqT + PickNet 得到震相到时之后，遍历所有的震相到时
2.对每个震相到时截取一个时窗，去趋势、预滤波、去仪器响应至位移、卷上Wood-Anderson仪器响应、滤波至0.2Hz-10Hz，并取窗内最大绝对振幅、并更新在震相文件的第三列上（原文件该列都是0.0000000)
3.之后再执行04_run_REAL.py ，输出的目录就带有震级了。

我计划加一个对应的例子，但是最近实在是事情有点多，大概两周内更新上把 ： ）

**Comment by Ma-yuan-science** [comment]
谢谢您
