### ISSUE TITLE
file name

### ISSUE THREAD

**Issue by Gaoya423** [MrXiaoXiao/ESPRH#10]
![image](https://user-images.githubusercontent.com/112377967/222877300-4b0244f2-1876-4bdb-825b-e41fdab8bccc.png)
肖老师，请问下我的波形文件的开始时间和结束时间都不是一个整时。在波形文件的命名上可以GS.WDT..BHE__20210930T000000Z__20211001T000000Z.mseed，这样化成整时吗？还是说需要将波形时间改成波形确切的开始和结束时间。对跑模型的结果有什么影响吗？

**Comment by MrXiaoXiao** [comment]
可以在命名上化成整时，程序里面是根据mseed里面的时间算的，对结果应该没有影响。

**Comment by Gaoya423** [comment]
好的，谢谢肖老师的回复
（ps:我用小数据测试了下，如果波形三份量文件命名都不一致的话，模型会将三份量文件分别认为是单独的文件）
