### ISSUE TITLE
关于不自动生成sta_info_real_format.dat和ori_dataxml文件的问题

### ISSUE THREAD

**Issue by GGeophysics** [MrXiaoXiao/ESPRH#12]
肖博士您好，在我运行example和用自己的数据进行测试的时候我遇到了一个问题：

01步骤运行后不能自动生成sta_info_real_format.dat，由此不能运行script02。同样我发现ori_dataxml文件夹也没有生成。随后我在环境中测试了import 没有发现问题。

请问您是否了解如何处理？

**Comment by MrXiaoXiao** [comment]
抱歉我最近在度假。请问您是否先运行了00脚本下载数据呢，看起来好像是没有下载数据的问题，example文件夹里面是没有波形文件的。如果不是没有下载数据的问题，您可以把01脚本的运行情况详细描述一下。

**Comment by GGeophysics** [comment]
感谢您的回复，我又研究了一遍代码，现在问题已经解决。应用流动台站的数据需要手动生成一份ori_dataxml供后续步骤调取。
