### ISSUE TITLE
连续处理多天数据

### ISSUE THREAD

**Issue by Ma-yuan-science** [MrXiaoXiao/ESPRH#2]
您好，请问该程序如何连续处理多天的数据，案例中似乎只能处理一天多台的数据。

**Comment by MrXiaoXiao** [comment]
您好，这个程序是可以处理多天的连续数据的。
以IRIS上下载的数据为例，只需要修改参数文件DataDownload下面的start_time和end_time即可。例如将end_time设置为起始时间之后的20天。
对于较长的时间周期，例如一年，建议写个单独的脚本，每20天一个小组，分配单独的taskID，写个循环每次修改参数文件并执行00-06脚本。

**Comment by Ma-yuan-science** [comment]
十分感谢您的解答
