### ISSUE TITLE
data.xml文件

### ISSUE THREAD

**Issue by Ma-yuan-science** [MrXiaoXiao/ESPRH#3]
您好，请问在使用自己的数据研究时，如何构建data.xml文件

**Comment by MrXiaoXiao** [comment]
您好，xml格式是FDSNStationXML格式，您可以参照obspy的示例创建自己数据对应的xml的文档。
https://docs.obspy.org/tutorial/code_snippets/stationxml_file_from_scratch.html

**Comment by shenxuanye** [comment]
请问一下，我在使用自己的数据时，按照样例创建了sta_info_real_format.dat，station_list.json文件，数据文件也按照样例名称作了更改，但是在使用01_EQT.py 时，显示列表值超过范围（我的数据采样率是100Hz，检查了sta_info_real_format.dat，station_list.json文件，都是按照格式创建的），请问一下，还需要更改哪些参数呢？
