### ISSUE TITLE
速度模型的使用

### ISSUE THREAD

**Issue by Ma-yuan-science** [MrXiaoXiao/ESPRH#4]
你好！请问您在区域大尺度上使用hypodd时，用一维速度模型进行地震定位的效果如何，是否需要先使用velest先去反演最新的速度模型。

**Comment by MrXiaoXiao** [comment]
大区域的话，可以使用velest先反演速度模型，或者有前人给出的比较准的速度模型也可以用。用velest反演的时候可以挑选震相多的地震，舍弃一些震相少的地震，这样反演更稳定一些。
PS: 年底事情太多了，之前您提的一些功能我还没加上。打算下周过后陆续更新上，抱歉哈。

**Comment by Ma-yuan-science** [comment]
非常感谢您的解答
