### ISSUE TITLE
使用hypoinverse

### ISSUE THREAD

**Issue by Ma-yuan-science** [MrXiaoXiao/ESPRH#5]
您好，我最近在使用hypoinverse程序进行地震定位，经过参数的调试，结果不是很理想，有半数以上的地震QASR标记D(bad)。我的研究区域情况和您的类似，都是区域尺度的（4°*5°），所以想请教一下您在使用hypoinverse时，参数调试上是否有什么注意事项或者技巧，另外我在使用hypoinverse前已经有了震级的结果，不太清楚震级是否会对地震的评价有影响。

**Comment by MrXiaoXiao** [comment]
您好，可能有一些需要注意的地方或者建议：
（1）您可以画一下地震 水平定位误差、 垂直定位误差 和 方位角gap 的分布，这些可能对控制地震目录质量更有帮助。例如，您可以对比误差在1km, 5km, 10km, 20km以内的地震分布图等；
（2）质量分类里面的方位角gap可以适当放松一下。在台站稀疏的情况下可能存在定位误差小但是方位角不是太好的情况；
（3）如果可以的话尽量使用当地比较可靠的速度模型；
（4）震级对评价应该没有影响，hypoInverse给地震评价应该主要依据水平垂直误差和gap；
（5）如果像这类不是直接跟程序bug相关的问题，您可以直接给我发邮件。如果需要的话可以线上会议沟通会方便一些。
