### ISSUE TITLE
数据无法完全下载

### ISSUE THREAD

**Issue by Gaoya423** [MrXiaoXiao/ESPRH#6]
肖老师，您好。我目前在试着跑您ESPRH里的S-EQP,在数据下载这块遇到了问题。其中GIB和TAPE的这两个台站信息无法下载，我这边网络没发到外网，能请教您有什么办法吗？

**Comment by Gaoya423** [comment]
肖老师，我还想请问下跑第二部分的eqt模型时，会出现IndexError: list index out of range，这是由于第一步的台站下载不完全导致的吗？

**Comment by MrXiaoXiao** [comment]
您好，关于数据下载，您可以在有网的环境下执行下载，然后把数据传到您的工作站上。
关于第二个问题，您可以提供更详细完整一些的错误信息么。比如具体是哪段报错的。
另外您执行后续步骤时可以参考下刚刚更新的常见问题说明。
如果问题比较复杂可以线上会议解决一下。

**Comment by Gaoya423** [comment]
好的，谢谢肖老师。目前第二个问题解决了，是由于有些地方代码格式不适用于Windows系统。

**Comment by Gaoya423** [comment]
好的，谢谢肖老师。目前第二个问题解决了，是由于有些地方代码格式不适用于Windows系统。
